import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Theme from "./theme-provider";
import { ToggleThemeButton } from "./toggle-theme-button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Theme>
          <ToggleThemeButton />
          <div className="grid-cols-app grid min-h-screen">
            <aside className="border-r border-zinc-200 px-5 py-8 dark:border-zinc-600">
              sidebar
            </aside>
            <main className="px-4 pb-12 pt-8">{children}</main>
          </div>
        </Theme>
      </body>
    </html>
  );
}
