import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Theme from "./theme-provider"
import { ToggleThemeButton } from "./toggle-theme-button"
import { Sidebar } from "@/components/Sidebar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Theme>
          <ToggleThemeButton />
          <div className="grid min-h-screen grid-cols-app dark:bg-zinc-900">
            <Sidebar />
            <main className="px-4 pb-12 pt-8">{children}</main>
          </div>
        </Theme>
      </body>
    </html>
  )
}
